import Head from "next/head"
import PageHeader from "../components/PageHeader";

const LazyPDF = () => {
const metaTitle = "KEJK | Lazy PDF";
return (
<div className={"mt-12"}>
      <Head>
        <title>{metaTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
<PageHeader>Coming soon</PageHeader>
</main>
</div>
)
};

export default LazyPDF;