import Head from "next/head";
import StackCard from "../components/StackCard";
import PageHeader from "../components/PageHeader";

const Cosmic = require("cosmicjs");
const api = Cosmic();

const BUCKET_SLUG = process.env.NEXT_PUBLIC_COSMIC_SLUG;
const READ_KEY = process.env.NEXT_PUBLIC_COSMIC_READ_KEY;

const bucket = api.bucket({
  slug: BUCKET_SLUG,
  read_key: READ_KEY,
});

export default function Projects({ stacks }) {
  const metaTitle = "KEJK | Stack";
  return (
    <div className={"mt-12"}>
      <Head>
        <title>{metaTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageHeader>Stack</PageHeader>
        <div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-3">
          {stacks.map((stack) => {
            return (
              <StackCard
                key={stack.id}
                link={stack.metadata.url}
                image={stack.metadata.icon.imgix_url}
                title={stack.title}
                subtitle={stack.metadata.subtitle}
                tags={stack.metadata.tags}
              />
            );
          })}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const data = await bucket.getObjects({
    query: {
      type: "software-stacks",
    },
    props: "title,content,metadata",
  });

  const stacks = await data.objects;
  return {
    props: {
      stacks,
    },
  };
}
